language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - SYMFONY_DEPRECATIONS_HELPER=strict
        - SYMFONY_VERSION=2.7.*
        - SYMFONY_PHPUNIT_BRIDGE_VERSION=2.7.*

install:
    - composer self-update
    - composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
    - composer require --no-update symfony/form:${SYMFONY_VERSION}
    - composer require --no-update symfony/twig-bundle:${SYMFONY_VERSION}
    - composer require --no-update symfony/asset:${SYMFONY_VERSION}
    - composer require --no-update symfony/templating:${SYMFONY_VERSION}
    - composer require --no-update symfony/yaml:${SYMFONY_VERSION}
    - composer require --dev --no-update symfony/phpunit-bridge:${SYMFONY_PHPUNIT_BRIDGE_VERSION}
    - if [[ "$SYMFONY_VERSION" = *dev* ]]; then sed -i "s/\"MIT\"/\"MIT\",\"minimum-stability\":\"dev\"/g" composer.json; fi
    - composer update --prefer-source `if [[ $COMPOSER_PREFER_LOWEST = true ]]; then echo "--prefer-lowest --prefer-stable"; fi`

script: phpunit

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.* SYMFONY_PHPUNIT_BRIDGE_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.0.* SYMFONY_PHPUNIT_BRIDGE_VERSION=3.0.* COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: SYMFONY_VERSION=3.1.* SYMFONY_PHPUNIT_BRIDGE_VERSION=3.1.*
        - php: 5.6
          env: SYMFONY_VERSION=3.2.* SYMFONY_PHPUNIT_BRIDGE_VERSION=3.2.*
        - php: 5.6
          env: SYMFONY_VERSION=3.3.*@dev SYMFONY_PHPUNIT_BRIDGE_VERSION=3.3.*@dev
    allow_failures:
        - env: SYMFONY_VERSION=3.3.*@dev SYMFONY_PHPUNIT_BRIDGE_VERSION=3.3.*@dev

notifications:
    email: trsteel88@gmail.com
